spring.application.name=pm

spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USER}
spring.datasource.password=${DATA_SOURCE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

#POSTGRES
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.servlet.context-path=/api
server.port=${SERVER_PORT}

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.url=/openapi.yaml
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/,classpath:/resources/

member.api.url=https://localhost:8089